from pathlib import Path

import yaml


DEFAULT_PROJECT = """\
name: my-project
version: 0.1.0
description: Enterprise AI Builder project

workflow: workflows/main.yaml

llm:
  provider: openai
  model: gpt-5.5
"""


DEFAULT_WORKFLOW = """\
name: main

steps:
  - id: welcome
    action: message
    text: "Welcome to Enterprise AI Builder!"
"""


DEFAULT_README = """\
# Enterprise AI Builder Project

This project was generated by Enterprise AI Builder.
"""


def create_project(path: str | Path) -> Path:
    """
    Create a new Enterprise AI Builder project.

    Returns:
        Path: Path tới project vừa được tạo.

    Raises:
        FileExistsError: Nếu project đã tồn tại.
    """

    path = Path(path)

    if path.exists():
        raise FileExistsError(f"Project already exists: {path}")

    path.mkdir(parents=True)

    directories = [
        "agents",
        "workflows",
        "plugins",
        "prompts",
        "knowledge",
        "output",
    ]

    for directory in directories:
        (path / directory).mkdir()

    (path / "project.yaml").write_text(
        DEFAULT_PROJECT,
        encoding="utf-8",
    )

    (path / "workflows" / "main.yaml").write_text(
        DEFAULT_WORKFLOW,
        encoding="utf-8",
    )

    (path / "README.md").write_text(
        DEFAULT_README,
        encoding="utf-8",
    )

    return path


def load_project(path: str | Path = ".") -> dict:
    """
    Load project.yaml from the specified directory.
    """

    path = Path(path)

    project_file = path / "project.yaml"

    if not project_file.exists():
        raise FileNotFoundError(
            f"project.yaml not found: {project_file.resolve()}"
        )

    with project_file.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def load_workflow(path: str | Path) -> dict:
    """
    Load a workflow YAML file.
    """

    workflow_file = Path(path)

    if not workflow_file.exists():
        raise FileNotFoundError(
            f"Workflow not found: {workflow_file.resolve()}"
        )

    with workflow_file.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)
