"""
Project creation logic for Enterprise AI Builder.
"""

from pathlib import Path

import yaml


DEFAULT_DIRECTORIES = [
    "agents",
    "workflows",
    "plugins",
    "prompts",
    "knowledge",
    "output",
]


def create_project(project_name: str) -> Path:
    """
    Create a new Enterprise AI Builder project.

    Returns:
        Path: Path to the created project directory.

    Raises:
        FileExistsError: If the target directory already exists.
    """

    project_dir = Path(project_name)

    if project_dir.exists():
        raise FileExistsError(
            f"Directory '{project_name}' already exists."
        )

    project_dir.mkdir(parents=True)

    for directory in DEFAULT_DIRECTORIES:
        (project_dir / directory).mkdir()

    config = {
        "name": project_name,
        "version": "0.1.0",
        "framework": "Enterprise AI Builder",
    }

    with open(project_dir / "project.yaml", "w", encoding="utf-8") as f:
        yaml.safe_dump(
            config,
            f,
            sort_keys=False,
            allow_unicode=True,
        )

    (project_dir / "README.md").write_text(
        f"# {project_name}\n\n"
        "Generated by Enterprise AI Builder.\n",
        encoding="utf-8",
    )

    return project_dir
